services:
  - type: web
    name: ci-analytics
    env: node
    rootDir: website
    buildCommand: npm install && npm run build
    startCommand: node ./dist/server/entry.mjs
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
